#!/bin/sh
rm hist1 hist.root

g++ -Wall `root-config --cflags --libs` -o hist1 AnalysisSteering.cc \
    Constants.cc Event.cc EventDump.cc EventReadFromFile.cc EventSim.cc \
    EventSource.cc MassMean.cc ParticleMass.cc Utilities.cc mass.cc main.cc
